'--- Color Setting --- 
' System is #DAE2F3
' Layer is #FEE599
' Component is #lightcyan
' Module is #E2EFD9
' Unit is #gainsboro
' Tiny is #pink
'---------------------

@startuml
'----- Table Description ----
'Object Colors Setting
skinparam defaultFontName Arial
skinparam defaultFontSize 12
legend top
|=        Object  |=           Colors  |
| System  |<back:mediumpurple>                                    |
| Layer  |<back:#FEE599>                                    |
| Component |<back:#lightcyan>                                    |
| Module |<back:#E2EFD9>                                    |
| Uint |<back:#aquamarine>                                    |
| Tiny |<back:#pink>                                    |
'Arrow Function
|=        Arrow |=        Description |
| Solid Line (->) | Don't response value  |
| Dotted Line (--->) | Response value |
endlegend

'---- Define "Application" component and colors ----
box "Application (SWAD-001)" #aef2f7
participant "SWAD-001-001\nMain" as Main #E2EFD9
participant "SWAD-001-004\nSmApp" as SmApp #E2EFD9
participant "SWAD-001-002\nInitApp" as InitApp #E2EFD9
participant "SWAD-001-007\nClkApp" as ClkApp #E2EFD9
participant "SWAD-001-003\nPinIoApp" as PinIoApp #E2EFD9
participant "SWAD-001-005\nRtosApp" as RtosApp #E2EFD9
participant "SWAD-001-006\nTaskApp" as TaskApp #E2EFD9
end box

'---- Define "Service" component--------------------
box "Service (SWAD-002)" #aef2f7
participant "SWAD-002-001\nUDS" as UDS #E2EFD9
participant "SWAD-002-002\nFuSa" as FuSa #E2EFD9
participant "SWAD-002-003\nSecurity" as Security #E2EFD9
end box

'---- Define "HAL" component -----------------------
box "HAL (SWAD-003)" #aef2f7
participant "SWAD-003-001\nClkHal" as ClkHal #E2EFD9
participant "SWAD-003-002\nPinIoHal" as PinIoHal #E2EFD9
end box

'---- Define "OS" component ------------------------
box "OS (SWAD-004)" #aef2f7
participant "SWAD-004-001\nfreeRTOS" as freeRTOS #E2EFD9
end box

'---- Define "Drivers" component -------------------
box "Drivers (SWAD-005)" #aef2f7
participant "SWAD-005-001\nClkDrv" as ClkDrv #E2EFD9
participant "SWAD-005-002\nPinIoDrv" as PinIoDrv #E2EFD9
end box

'---- Define "Hardware" layer ----------------------
participant Hardware #mediumpurple

'---- Plan modules sequence-------------------------
Main -> SmApp: Change to SM_INIT state
activate SmApp
SmApp -> InitApp
activate InitApp
InitApp -> ClkApp: Init Clks
activate ClkApp
ClkApp -> ClkHal
activate ClkHal
ClkHal -> ClkDrv
activate  ClkDrv
ClkDrv -> Hardware: Enable clock sources
activate Hardware
Hardware --> ClkDrv
deactivate Hardware
ClkDrv --> ClkHal
deactivate ClkDrv 
ClkHal --> ClkApp
deactivate ClkHal 
ClkApp --> InitApp
deactivate ClkApp 
InitApp -->PinIoApp 
activate PinIoApp 
PinIoApp -> PinIoHal: Init PinIOs
activate PinIoHal
PinIoHal -> PinIoDrv
activate PinIoDrv
PinIoDrv -> Hardware: Drive GPIOs
activate Hardware
Hardware --> PinIoDrv 
deactivate Hardware
PinIoDrv --> PinIoHal
deactivate PinIoDrv
PinIoHal --> PinIoApp
deactivate PinIoHal
PinIoApp --> InitApp
deactivate PinIoApp 
InitApp -> RtosApp
activate  RtosApp
RtosApp -> freeRTOS: Tasks config
activate freeRTOS
freeRTOS --> RtosApp: Initialize finish
deactivate freeRTOS
RtosApp --> InitApp
deactivate RtosApp

InitApp --> SmApp
deactivate InitApp
deactivate SmApp
SmApp -> TaskApp: Change to SM_TASK state

TaskApp -> PinIoHal: GPIO sensing every 1s
activate PinIoHal
PinIoHal -> PinIoDrv
activate PinIoDrv
PinIoDrv -> Hardware
activate Hardware
Hardware --> PinIoDrv
deactivate Hardware
PinIoDrv --> PinIoHal
deactivate PinIoDrv
PinIoHal --> TaskApp 
deactivate PinIoHal
'---------------------------------------------------
@enduml
