@startuml
'----- Table Description ----
'Object Colors Setting
skinparam defaultFontName Arial
skinparam defaultFontSize 12
legend top
|=        Object  |=           Colors  |
| Microcontroller  |<back:#A0522D>                                    |
| System  |<back:#9370DB>                                    |
| Layer  |<back:#FEE599>                                    |
| Component |<back:#E0FFFF>                                    |
| Module |<back:#E2EFD9>                                    |
| Uint |<back:#7FFFD4>                                    |
| Tiny |<back:#FFC0CB>                                    |
'Arrow Function
|=        Arrow |=        Description |
| Solid Line (->) | Don't response value  |
| Dotted Line (--->) | Response value |
endlegend

'---- Define "Application" component and colors ----
box "Application (SWAD-001)" #aef2f7
participant "SWAD-001-001\nMain" as Main #E2EFD9
participant "SWAD-001-004\nSmApp" as SmApp #E2EFD9
participant "SWAD-001-002\nInitApp" as InitApp #E2EFD9
participant "SWAD-001-007\nClkApp" as ClkApp #E2EFD9
participant "SWAD-001-003\nPinIoApp" as PinIoApp #E2EFD9
participant "SWAD-001-005\nRtosApp" as RtosApp #E2EFD9
participant "SWAD-001-006\nTaskApp" as TaskApp #E2EFD9
end box

'---- Define "Service" component--------------------
box "Service (SWAD-002)" #aef2f7
participant "SWAD-002-001\nUDS" as UDS #E2EFD9
participant "SWAD-002-002\nFuSa" as FuSa #E2EFD9
participant "SWAD-002-003\nSecurity" as Security #E2EFD9
end box

'---- Define "HAL" component -----------------------
box "HAL (SWAD-003)" #aef2f7
participant "SWAD-003-001\nClkHal" as ClkHal #E2EFD9
participant "SWAD-003-002\nPinIoHal" as PinIoHal #E2EFD9
end box

'---- Define "OS" component ------------------------
box "OS (SWAD-004)" #aef2f7
participant "freeRTOS Modules" as RtosModules #E2EFD9
end box

'---- Define "Drivers" component -------------------
box "Drivers (SWAD-005)" #aef2f7
participant "SWAD-005-001\nClkDrv" as ClkDrv #E2EFD9
participant "SWAD-005-002\nPinIoDrv" as PinIoDrv #E2EFD9
end box

'---- Define "Hardware" layer ----------------------
participant Microcontroller #A0522D

'---- Plan modules sequence-------------------------
Main -> SmApp: Change to SM_INIT state
activate SmApp
SmApp -> InitApp
activate InitApp
InitApp -> ClkApp: Init Clks
activate ClkApp
ClkApp -> ClkHal
activate ClkHal
ClkHal -> ClkDrv
activate  ClkDrv
ClkDrv -> Microcontroller: Enable clock sources
activate Microcontroller
Microcontroller --> ClkDrv
deactivate Microcontroller
ClkDrv --> ClkHal
deactivate ClkDrv 
ClkHal --> ClkApp
deactivate ClkHal 
ClkApp --> InitApp
deactivate ClkApp 
InitApp -->PinIoApp 
activate PinIoApp 
PinIoApp -> PinIoHal: Init PinIOs
activate PinIoHal
PinIoHal -> PinIoDrv
activate PinIoDrv
PinIoDrv -> Microcontroller: Drive GPIOs
activate Microcontroller
Microcontroller --> PinIoDrv 
deactivate Microcontroller
PinIoDrv --> PinIoHal
deactivate PinIoDrv
PinIoHal --> PinIoApp
deactivate PinIoHal
PinIoApp --> InitApp
deactivate PinIoApp 
InitApp -> RtosApp
activate  RtosApp
RtosApp -> RtosModules: Tasks config
activate RtosModules
RtosModules --> RtosApp: Initialize finish
deactivate RtosModules
RtosApp --> InitApp
deactivate RtosApp

InitApp --> SmApp
deactivate InitApp
deactivate SmApp
SmApp -> TaskApp: Change to SM_TASK state

TaskApp -> PinIoHal: GPIO sensing every 1s
activate PinIoHal
PinIoHal -> PinIoDrv
activate PinIoDrv
PinIoDrv -> Microcontroller
activate Microcontroller
Microcontroller --> PinIoDrv
deactivate Microcontroller
PinIoDrv --> PinIoHal
deactivate PinIoDrv
PinIoHal --> TaskApp 
deactivate PinIoHal
'---------------------------------------------------
@enduml
